export const PARKING_SPACE_LIST = 'Parking Space';
export const PARKING_SPACE_DETAIL = 'Parking Space detail';
export const PARKING_LOT_ATTENDANT_LIST = 'Parking Lot Attendants'
export const CREATE_PARKING_SPACE = 'Create Parking Space';
export const SETTINGS = 'Settings';
export const LOGIN = 'Login';
export const REGISTER = 'Register';
export const HOME_NAVIGATOR = 'Home';
export const LOGOUT = 'LOGOUT';
export const ADD_PARKING_LOT_ATTENDANT = "Add Parking Lot Attendant"
export const REQUEST_QR_CODE = "Request QR Code"
export const CHECKED_IN_PARKING_SPACE = "CHECKED_IN_PARKING_SPACE"
export const CHECK_IN = "CHECK_IN"
export const PARKING_RESERVATION_DETAIL = "Parking Reservation Detail"
export const UPDATE_PROFILE = "Update Profile"
export const UPDATE_PASSWORD = "Update Password"
export const RESET_PASSWORD = "Reset Password"
export const PARKING_SPACE_REPORT = "Parking Space Report"
