export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const GET_CONTACTS_LOADING = 'GET_CONTACTS_LOADING';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';

export const GET_PARKING_SPACES_LOADING = 'GET_PARKING_SPACES_LOADING';
export const GET_PARKING_SPACES_SUCCESS = 'GET_PARKING_SPACES_SUCCESS';
export const GET_PARKING_SPACES_FAIL = 'GET_PARKING_SPACES_FAIL';

export const GET_PARKING_LOT_ATTENDANTS_LOADING =
  'GET_PARKING_LOT_ATTENDANTS_LOADING';
export const GET_PARKING_LOT_ATTENDANTS_SUCCESS =
  'GET_PARKING_LOT_ATTENDANTS_SUCCESS';
export const GET_PARKING_LOT_ATTENDANTS_FAIL =
  'GET_PARKING_LOT_ATTENDANTS_FAIL';

export const REMOVE_PARKING_LOT_ATTENDANT_LOADING =
  'REMOVE_PARKING_LOT_ATTENDANT_LOADING';
export const REMOVE_PARKING_LOT_ATTENDANT_SUCCESS =
  'REMOVE_PARKING_LOT_ATTENDANT_SUCCESS';
export const REMOVE_PARKING_LOT_ATTENDANT_FAIL =
  'REMOVE_PARKING_LOT_ATTENDANT_FAIL';

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';

export const CREATE_PARKING_SPACE_LOADING = 'CREATE_PARKING_SPACE_LOADING';
export const CREATE_PARKING_SPACE_SUCCESS = 'CREATE_PARKING_SPACE_SUCCESS';
export const CREATE_PARKING_SPACE_FAIL = 'CREATE_PARKING_SPACE_FAIL';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const DELETE_PARKING_SPACE_LOADING = 'DELETE_PARKING_SPACE_LOADING';
export const DELETE_PARKING_SPACE_SUCCESS = 'DELETE_PARKING_SPACE_SUCCESS';
export const DELETE_PARKING_SPACE_FAIL = 'DELETE_PARKING_SPACE_FAIL';

export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';

export const EDIT_PARKING_SPACE_LOADING = 'EDIT_PARKING_SPACE_LOADING';
export const EDIT_PARKING_SPACE_SUCCESS = 'EDIT_PARKING_SPACE_SUCCESS';
export const EDIT_PARKING_SPACE_FAIL = 'EDIT_PARKING_SPACE_FAIL';
export const ADD_PARKING_LOT_ATTENDANTS_SUCCESS =
  'ADD_PARKING_LOT_ATTENDANTS_SUCCESS';

export const SET_SELECTED_PARKING_SPACE = 'SET_SELECTED_PARKING_SPACE';
export const REMOVE_SELECTED_PARKING_SPACE = 'REMOVE_SELECTED_PARKING_SPACE';
